## Append samples you want in your CSV to this file as resources ##
resources:
- _v1alpha1_hazelcast.yaml
- _v1alpha1_managementcenter.yaml
- _v1alpha1_map.yaml
- _v1alpha1_wanreplication.yaml
- _v1alpha1_multimap.yaml
- _v1alpha1_cronhotbackup.yaml
- _v1alpha1_topic.yaml
- _v1alpha1_replicatedmap.yaml
- _v1alpha1_queue.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
