## Append samples you want in your CSV to this file as resources ##
resources:
- _v1alpha1_hazelcast.yaml
- _v1alpha1_managementcenter.yaml
- _v1alpha1_turbine.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
