name: (3) Community Operator Tests
on:
  workflow_call:
    inputs:
      BUNDLE_VERSION:
        required: true
        type: string

env:
  HZ_OPERATOR_NAME: "hazelcast-platform-operator"
  SCRIPT_URL: https://raw.githubusercontent.com/redhat-openshift-ecosystem/community-operators-pipeline/ci/latest/ci/scripts/opp.sh
  OPP_DEBUG: 1
  OPP_PRODUCTION_TYPE: k8s
  PARDOT_ID: redhat

jobs:
  community-operators-test-suite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testType: [ kiwi, lemon, orange ]
      fail-fast: true

    steps:
      - name: Checkout community-operators
        uses: actions/checkout@v3
        with:
          repository: k8s-operatorhub/community-operators
          path: community-operators

      - name: Create Release Directory
        working-directory: community-operators
        run: |
          echo "Creating operator release folder"
          mkdir -p operators/${{ env.HZ_OPERATOR_NAME }}/${{ inputs.BUNDLE_VERSION }}

      - name: Download Bundle Artifacts
        uses: actions/download-artifact@v3
        with:
          name: bundle-artifacts
          path: community-operators/operators/${{ env.HZ_OPERATOR_NAME }}/${{ inputs.BUNDLE_VERSION }}

      - name: Test Suite
        working-directory: community-operators
        run: bash <(curl -sL $SCRIPT_URL) ${{ matrix.testType }} operators/$HZ_OPERATOR_NAME/${{ inputs.BUNDLE_VERSION }}
        shell: 'script -q -e -c "bash {0}"'