name: Helm Chart Sync

on:
  push:
    paths:
      - 'helm-charts/**'
    branches:
      - main

jobs:
  push-new-chart-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEVOPS_GITHUB_TOKEN }}

      - name: Commit And Push Changes To 'Hazelcast Charts' Repository
        run: |
          echo ${{ secrets.DEVOPS_GITHUB_TOKEN }} | gh auth login --with-token
          git config user.email "devopshelm@hazelcast.com"
          git config user.name "devOpsHelm"
          git subtree add --prefix=charts https://github.com/hazelcast/charts.git master --squash
          cp -rf helm-charts/hazelcast-platform-operator/* charts/stable/hazelcast-platform-operator
          git add charts/
          git commit --signoff -m "${{github.event.head_commit.message}}"
          git subtree push --prefix=charts https://github.com/hazelcast/charts.git master
