name: Nightly PhoneHome tests on GKE
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

env:
  GCP_PROJECT_ID: hazelcast-33
  GKE_ZONE: europe-west1-b
  BIG_QUERY_TABLE: hazelcast-33.callHome.operator_info
  NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}

jobs:
  create-gke-cluster:
    name: Create GKE cluster
    runs-on: ubuntu-latest
    outputs:
      CLUSTER_NAME: ${{ steps.set-cluster-name.outputs.CLUSTER_NAME }}
    env:
      GCP_NETWORK: operator-test-network
    steps:
      - name: Authenticate to GCP
        uses: 'google-github-actions/auth@v0.8.1'
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Create GKE cluster
        id: set-cluster-name
        run: |-
          CLUSTER_NAME="operator-ph-test-${GITHUB_SHA::8}-${GITHUB_RUN_NUMBER}"
          echo "::set-output name=CLUSTER_NAME::${CLUSTER_NAME}"
          gcloud container clusters create ${CLUSTER_NAME} \
            --zone=${{ env.GKE_ZONE }} \
            --project=${{ env.GCP_PROJECT_ID }} \
            --network=${{ env.GCP_NETWORK }} \
            --machine-type=n1-standard-2 \
            --num-nodes=3
          sleep 30

  new-relic-setup:
    needs: [create-gke-cluster]
    uses: ./.github/workflows/newrelic-gke.yaml
    secrets: inherit
    with:
      cluster_name: ${{ needs.create-gke-cluster.outputs.CLUSTER_NAME }}
      nr_cluster_name: phone-home-operator
      gh_run_id: ${{ github.run_id }}
      gh_run_number: ${{ github.run_number }}
      gh_sha: ${{ github.sha }}

  get-image:
    name: Get Image
    runs-on: ubuntu-latest
    outputs:
      IMG: ${{ steps.build-img.outputs.IMG }}
      VERSION: ${{ steps.build-img.outputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push image to ttl.sh
        id: build-img
        run: |
          if [[ "${{github.event_name}}" == "workflow_dispatch" ]]; then
            IMG=ttl.sh/$(uuidgen):2h
            make docker-build-ci IMG=$IMG VERSION=${{github.sha}}
            make docker-push IMG=$IMG
            echo "::set-output name=IMG::${IMG}"
            echo "::set-output name=VERSION::${{github.sha}}"
          else
            IMG=hazelcast/hazelcast-platform-operator:latest-snapshot
            echo "::set-output name=IMG::${IMG}"
            echo "::set-output name=VERSION::latest-snapshot"
          fi

  gke-ph-tests:
    name: Run PhoneHome tests
    runs-on: ubuntu-latest
    needs: [create-gke-cluster, new-relic-setup, get-image]
    env:
      IMG: ${{ needs.get-image.outputs.IMG }}
      VERSION: ${{ needs.get-image.outputs.VERSION }}
      NAMESPACE: test-operator-ph-nightly-ee
      PHONE_HOME_ENABLED: true
      CLUSTER_NAME: ${{ needs.create-gke-cluster.outputs.CLUSTER_NAME }}
      NAME_PREFIX: hp-ee-${{ github.run_id }}-

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Golang dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Authenticate to GCP
        uses: "google-github-actions/auth@v0.8.1"
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Connect to the GKE cluster
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
            --zone ${{ env.GKE_ZONE }} \
            --project ${{ env.GCP_PROJECT_ID }}

      - name: Deploy Operator to GKE
        run: |
          kubectl create namespace ${{ env.NAMESPACE }}
          kubectl config set-context --current --namespace=$NAMESPACE

          DEPLOY_NAME=${NAME_PREFIX}controller-manager
          echo "DEPLOY_NAME=${DEPLOY_NAME}" >> $GITHUB_ENV

          make deploy IMG=$IMG NAMESPACE=$NAMESPACE NAME_PREFIX=$NAME_PREFIX PHONE_HOME_ENABLED=${{ env.PHONE_HOME_ENABLED }}
          kubectl rollout status deployment $DEPLOY_NAME

      - name: Create secrets
        run: |
          kubectl create secret generic hazelcast-license-key \
            --namespace ${{ env.NAMESPACE }} --from-literal=license-key=${{ secrets.HZ_LICENSE_KEY }}

      - name: Run Hazelcast Phone Home tests at GKE
        id: ph-test
        run: |
          GO_TEST_FLAGS=-ee=true
          make test-ph GO_TEST_FLAGS=${GO_TEST_FLAGS} NAMESPACE=$NAMESPACE NAME_PREFIX=$NAME_PREFIX WORKFLOW_ID=ph

      - name: Clean up after Tests
        if: always()
        run: |
          make clean-up-namespace NAMESPACE=${NAMESPACE}

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: allure-results/ph/

  report-generation:
    needs: ["create-gke-cluster", "gke-ph-tests"]
    if: always()
    uses: ./.github/workflows/generate-test-report.yaml
    secrets: inherit
    with:
      WORKFLOW_ID: ph

  delete-cluster:
    name: Delete PhoneHome cluster
    runs-on: ubuntu-latest
    if: always()
    needs: [create-gke-cluster, gke-ph-tests]
    env:
      CLUSTER_NAME: ${{ needs.create-gke-cluster.outputs.CLUSTER_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: "google-github-actions/auth@v0.8.1"
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Delete GKE cluster
        run: |-
          gcloud container clusters delete ${{ env.CLUSTER_NAME }} --zone ${{ env.GKE_ZONE }} --quiet

  slack_notify:
    name: Slack Notify
    needs: ["gke-ph-tests", "delete-cluster"]
    if: always() &&  ( needs.gke-ph-tests.result != 'success' || needs.delete-cluster.result != 'success')
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@22048831299719d772f51719ca7384e34b4cc61d
        with:
          fields: repo,commit,author,action,eventName,workflow
          status: failure
          channel: "#github-actions-log"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
